import type { Tool } from './types'

export const toolsData: Tool[] = [
  {
    id: '1', slug: 'lemon-squeezy', name: 'Lemon Squeezy',
    tagline: 'Merchant of record for software makers.',
    description: 'Handle payments, subscriptions, taxes, and global compliance. Acts as your merchant of record so you never deal with VAT paperwork. Built for digital products and SaaS.',
    category: 'payments', pricing: 'paid', stage: ['early', 'growth', 'scale'],
    affiliateUrl: 'https://lemonsqueezy.com', logoColor: '#F59E0B', logoInitial: 'LS',
    monthlyPrice: '0 + 5% per transaction', freeTier: false,
    pros: ['No monthly fee to start', 'Handles global VAT automatically', 'Built-in affiliate system', 'Simple payout flow'],
    cons: ['5% fee higher than Stripe', 'No in-person payments', 'Limited invoice customization'],
    tags: ['payments', 'subscriptions', 'digital products', 'merchant of record'],
    alternatives: ['stripe', 'paddle'],
    rating: 4.6, saves: 892, website: 'https://lemonsqueezy.com',
  },
  {
    id: '2', slug: 'supabase', name: 'Supabase',
    tagline: 'Open source Firebase with a real Postgres database.',
    description: 'Instant APIs, edge functions, auth, realtime, and storage. Built on Postgres — you own your data. Generous free tier makes it the default for indie SaaS.',
    category: 'database', pricing: 'open-source', stage: ['pre-launch', 'early', 'growth', 'scale'],
    affiliateUrl: 'https://supabase.com', logoColor: '#3ECF8E', logoInitial: 'SB',
    monthlyPrice: 'Free / $25 per project', freeTier: true,
    pros: ['Full Postgres with SQL support', 'Auth + storage out of the box', 'Generous free tier', 'Active OSS community'],
    cons: ['Cold starts on free tier', 'Self-hosting is complex', 'Realtime costs scale quickly'],
    tags: ['database', 'postgres', 'auth', 'storage', 'realtime'],
    alternatives: ['planetscale', 'neon', 'firebase'],
    rating: 4.8, saves: 1204, website: 'https://supabase.com',
  },
  {
    id: '3', slug: 'railway', name: 'Railway',
    tagline: 'Deploy any stack in seconds, no infra babysitting.',
    description: 'Provision databases, deploy services, and manage environments without touching AWS. Connects to your GitHub repo and handles the rest. Built for speed.',
    category: 'deployment', pricing: 'freemium', stage: ['pre-launch', 'early', 'growth'],
    affiliateUrl: 'https://railway.app', logoColor: '#B45FE4', logoInitial: 'RW',
    monthlyPrice: 'Free / $5 hobby', freeTier: true,
    pros: ['Zero config deploys', 'Built-in managed databases', 'Generous trial credits', 'Monorepo support'],
    cons: ['Less battle-tested than Heroku', 'No multi-region on lower plans', 'Docs still maturing'],
    tags: ['deployment', 'hosting', 'paas', 'docker'],
    alternatives: ['vercel', 'render', 'fly-io'],
    rating: 4.5, saves: 763, website: 'https://railway.app',
  },
  {
    id: '4', slug: 'vercel', name: 'Vercel',
    tagline: 'The frontend cloud. Deploy Next.js instantly.',
    description: 'Push to GitHub, live in 30 seconds. Global CDN, preview deployments per PR, edge functions, and the best Next.js DX on the market. Standard choice for frontend.',
    category: 'deployment', pricing: 'freemium', stage: ['pre-launch', 'early', 'growth', 'scale'],
    affiliateUrl: 'https://vercel.com', logoColor: '#0d1117', logoInitial: 'VC',
    monthlyPrice: 'Free / $20 pro', freeTier: true,
    pros: ['Best Next.js experience', 'Instant preview URLs', 'Global edge network', 'Analytics built in'],
    cons: ['Gets expensive at scale', 'Vendor lock-in risk', 'Serverless cold starts'],
    tags: ['deployment', 'frontend', 'nextjs', 'cdn', 'edge'],
    alternatives: ['railway', 'netlify', 'cloudflare-pages'],
    rating: 4.9, saves: 1887, website: 'https://vercel.com',
  },
  {
    id: '5', slug: 'plausible', name: 'Plausible Analytics',
    tagline: 'Privacy-first analytics that your users actually accept.',
    description: 'GDPR-compliant, cookie-free analytics with a clean dashboard. No tracking consent banners needed. Integrates in one script tag. Self-hostable.',
    category: 'analytics', pricing: 'paid', stage: ['pre-launch', 'early', 'growth'],
    affiliateUrl: 'https://plausible.io', logoColor: '#5850EC', logoInitial: 'PL',
    monthlyPrice: '$9/mo (up to 10k pageviews)', freeTier: false,
    pros: ['No cookie consent needed', 'Clean single-page dashboard', 'GDPR compliant by default', 'Self-hostable'],
    cons: ['No heatmaps or recordings', 'Costs add up at scale', 'Limited funnel analysis'],
    tags: ['analytics', 'privacy', 'gdpr', 'no-cookie'],
    alternatives: ['posthog', 'fathom', 'umami'],
    rating: 4.7, saves: 634, website: 'https://plausible.io',
  },
  {
    id: '6', slug: 'clerk', name: 'Clerk',
    tagline: 'Auth that takes 10 minutes, not 10 days.',
    description: 'Drop-in auth with pre-built UI components for sign-in, sign-up, user profiles, and organizations. MFA, social login, and magic links included. Next.js native.',
    category: 'auth', pricing: 'freemium', stage: ['pre-launch', 'early', 'growth'],
    affiliateUrl: 'https://clerk.com', logoColor: '#6C47FF', logoInitial: 'CK',
    monthlyPrice: 'Free up to 10k MAUs / $25+', freeTier: true,
    pros: ['Gorgeous pre-built UI', 'Next.js middleware integration', 'Organizations out of the box', 'Webhooks for user events'],
    cons: ['Vendor lock-in for auth flow', 'Pricey past free tier', 'Limited customization on free'],
    tags: ['auth', 'authentication', 'user management', 'nextjs'],
    alternatives: ['supabase', 'auth0', 'lucia'],
    rating: 4.8, saves: 1102, website: 'https://clerk.com',
  },
  {
    id: '7', slug: 'posthog', name: 'PostHog',
    tagline: 'Product analytics, session recording, and feature flags in one.',
    description: 'Self-host or use the cloud. Funnels, cohorts, A/B tests, feature flags, and session replays unified. The open-source Mixpanel alternative built for engineers.',
    category: 'analytics', pricing: 'open-source', stage: ['early', 'growth', 'scale'],
    affiliateUrl: 'https://posthog.com', logoColor: '#F54E00', logoInitial: 'PH',
    monthlyPrice: 'Free up to 1M events / then usage', freeTier: true,
    pros: ['Fully open source', 'Feature flags + A/B tests included', 'Session recordings', 'SQL access to your data'],
    cons: ['UI can feel overwhelming', 'Self-hosting requires infra', 'Complex for simple analytics needs'],
    tags: ['analytics', 'product analytics', 'feature flags', 'session replay'],
    alternatives: ['plausible', 'mixpanel', 'amplitude'],
    rating: 4.7, saves: 941, website: 'https://posthog.com',
  },
  {
    id: '8', slug: 'beehiiv', name: 'Beehiiv',
    tagline: 'The newsletter platform built by newsletter operators.',
    description: 'Grow, monetize, and analyze your email list. Built-in referral program, ad network, paid subscriptions, and a web presence. Favored by serious newsletter creators.',
    category: 'email', pricing: 'freemium', stage: ['pre-launch', 'early', 'growth', 'scale'],
    affiliateUrl: 'https://beehiiv.com', logoColor: '#FFDD00', logoInitial: 'BH',
    monthlyPrice: 'Free up to 2.5k subs / $42+', freeTier: true,
    pros: ['Built-in monetization tools', 'Referral program built in', 'Clean editor and templates', 'Strong analytics'],
    cons: ['Branding on free plan', 'Migration from Substack is clunky', 'No full marketing automation'],
    tags: ['email', 'newsletter', 'monetization', 'audience'],
    alternatives: ['substack', 'convertkit', 'mailchimp'],
    rating: 4.6, saves: 718, website: 'https://beehiiv.com',
  },
  {
    id: '9', slug: 'resend', name: 'Resend',
    tagline: 'Email API developers actually enjoy using.',
    description: 'Send transactional emails with React components. Built-in DKIM/SPF, high deliverability, real-time webhooks, and a dashboard with per-email analytics. Made for devs.',
    category: 'email', pricing: 'freemium', stage: ['pre-launch', 'early', 'growth'],
    affiliateUrl: 'https://resend.com', logoColor: '#0F172A', logoInitial: 'RS',
    monthlyPrice: 'Free 100 emails/day / $20+', freeTier: true,
    pros: ['React email components', 'Simple REST API', 'High deliverability', 'Generous free tier'],
    cons: ['No marketing email feature', 'Limited scheduling on free', 'Newer — less community resources'],
    tags: ['email', 'transactional', 'api', 'react-email'],
    alternatives: ['sendgrid', 'postmark', 'mailgun'],
    rating: 4.9, saves: 867, website: 'https://resend.com',
  },
  {
    id: '10', slug: 'tally', name: 'Tally',
    tagline: 'Beautiful forms, free forever. No per-response fees.',
    description: 'Notion-like form builder with conditional logic, file uploads, payments, and embeds. Notion-style UX makes creating complex forms feel effortless. Unlimited responses.',
    category: 'forms', pricing: 'freemium', stage: ['pre-launch', 'early', 'growth'],
    affiliateUrl: 'https://tally.so', logoColor: '#1A1A2E', logoInitial: 'TL',
    monthlyPrice: 'Free forever / $29 pro', freeTier: true,
    pros: ['Unlimited responses on free', 'Notion-style builder', 'Stripe payments built in', 'Embeds anywhere'],
    cons: ['Tally branding on free', 'Limited team features', 'No native CRM integrations'],
    tags: ['forms', 'surveys', 'no-code', 'data-collection'],
    alternatives: ['typeform', 'jotform', 'airtable-forms'],
    rating: 4.7, saves: 582, website: 'https://tally.so',
  },
  {
    id: '11', slug: 'cal-com', name: 'Cal.com',
    tagline: 'Open source scheduling that you actually own.',
    description: 'Self-hostable Calendly alternative. Supports team booking, round-robin, paid bookings, workflows, and 700+ integrations. Your data, your infrastructure.',
    category: 'scheduling', pricing: 'open-source', stage: ['pre-launch', 'early', 'growth', 'scale'],
    affiliateUrl: 'https://cal.com', logoColor: '#111827', logoInitial: 'CA',
    monthlyPrice: 'Free / $15 team', freeTier: true,
    pros: ['Fully open source', 'Self-hostable', 'Paid booking support', 'Zapier/n8n integrations'],
    cons: ['Self-hosting requires DevOps', 'Cloud version less competitive on price', 'Mobile UX lags behind Calendly'],
    tags: ['scheduling', 'booking', 'open-source', 'calendar'],
    alternatives: ['calendly', 'savvycal', 'tidycal'],
    rating: 4.6, saves: 491, website: 'https://cal.com',
  },
  {
    id: '12', slug: 'linear', name: 'Linear',
    tagline: 'Issue tracking that moves as fast as you do.',
    description: 'Keyboard-first project management designed for speed. Cycles, roadmaps, Git sync, and a UI that stays out of your way. The tool that replaced Jira for indie teams.',
    category: 'crm', pricing: 'freemium', stage: ['early', 'growth', 'scale'],
    affiliateUrl: 'https://linear.app', logoColor: '#5E6AD2', logoInitial: 'LN',
    monthlyPrice: 'Free up to 250 issues / $8 seat', freeTier: true,
    pros: ['Extremely fast UI', 'Git branch + PR linking', 'Keyboard-first workflow', 'Roadmap built in'],
    cons: ['Not for non-technical teams', 'Free plan is limited', 'No time tracking'],
    tags: ['project management', 'issues', 'roadmap', 'engineering'],
    alternatives: ['jira', 'height', 'plane'],
    rating: 4.9, saves: 1034, website: 'https://linear.app',
  },
]
