"""60 curated tools across 12 categories — (slug,name,tagline,cat,pricing,stage,url,pros,cons)."""
TOOLS = [
    # ── AUTH (5) ──────────────────────────────────────────────────────────────
    ("clerk","Clerk","Auth & user management platform","auth","freemium","idea,mvp,growth","https://clerk.com",'["Easy setup","Beautiful UI","SOC2 compliant"]','["Cost at scale","Vendor lock-in"]'),
    ("auth0","Auth0","Identity platform for developers","auth","freemium","mvp,growth,scale","https://auth0.com",'["Mature & flexible","Enterprise-ready","Many integrations"]','["Complex pricing","Steep learning curve"]'),
    ("supabase-auth","Supabase Auth","Open-source Firebase-alternative auth","auth","freemium","idea,mvp,growth","https://supabase.com/auth",'["Free tier","Postgres-native","Open source"]','["Self-host complexity","Newer platform"]'),
    ("firebase-auth","Firebase Auth","Google-backed auth infrastructure","auth","freemium","idea,mvp,growth","https://firebase.google.com/products/auth",'["Google reliability","Generous free tier","Social logins"]','["Vendor lock-in","NoSQL ecosystem"]'),
    ("nextauth","NextAuth.js","Authentication for Next.js","auth","free","idea,mvp","https://next-auth.js.org",'["Free forever","Flexible adapters","TypeScript-first"]','["Manual setup","No hosted UI option"]'),
    # ── PAYMENTS (5) ─────────────────────────────────────────────────────────
    ("stripe","Stripe","Payments infrastructure for the internet","payments","paid","mvp,growth,scale","https://stripe.com",'["Best-in-class docs","Highly reliable","Feature-rich"]','["2.9%+30¢ fees","Complex for simple use cases"]'),
    ("paddle","Paddle","Revenue delivery platform with MoR","payments","paid","growth,scale","https://paddle.com",'["Handles VAT/tax globally","Merchant of Record","Good dashboard"]','["Higher fees than Stripe","Less developer control"]'),
    ("lemon-squeezy","Lemon Squeezy","All-in-one SaaS payments & licensing","payments","paid","idea,mvp,growth","https://lemonsqueezy.com",'["Indie-friendly","Easy setup","License key support"]','["Newer platform","Limited customization"]'),
    ("gumroad","Gumroad","Sell digital products instantly","payments","paid","idea,mvp","https://gumroad.com",'["Zero monthly fee","Instant setup","Creator community"]','["10% flat fee","Basic feature set"]'),
    ("chargebee","Chargebee","Subscription billing & revenue ops","payments","freemium","growth,scale","https://chargebee.com",'["Powerful billing logic","Dunning management","Revenue recognition"]','["Pricey at scale","Complex initial setup"]'),
    # ── EMAIL (5) ─────────────────────────────────────────────────────────────
    ("resend","Resend","Email API built for developers","email","freemium","idea,mvp,growth","https://resend.com",'["Modern API","React Email support","Great DX"]','["Newer platform","Limited marketing templates"]'),
    ("mailgun","Mailgun","Transactional email API service","email","freemium","mvp,growth","https://mailgun.com",'["Reliable delivery","Detailed logs","EU hosting option"]','["Free tier reduced recently","Dated UI"]'),
    ("sendgrid","SendGrid","Cloud email delivery service","email","freemium","mvp,growth,scale","https://sendgrid.com",'["Highly scalable","Good analytics","Twilio-backed reliability"]','["Complex pricing tiers","Support issues reported"]'),
    ("postmark","Postmark","Fast, reliable transactional email","email","paid","mvp,growth","https://postmarkapp.com",'["Best deliverability","Near-instant delivery","Clean API"]','["No free tier","Transactional only"]'),
    ("convertkit","ConvertKit","Email marketing for creators","email","freemium","idea,mvp,growth","https://convertkit.com",'["Audience-first features","Automation sequences","Landing pages"]','["Not for transactional email","Pricier than alternatives"]'),
    # ── ANALYTICS (5) ────────────────────────────────────────────────────────
    ("mixpanel","Mixpanel","Product analytics for user behavior","analytics","freemium","mvp,growth","https://mixpanel.com",'["Powerful funnel analysis","Generous free tier","Event-based model"]','["Steep learning curve","Expensive at scale"]'),
    ("posthog","PostHog","Open-source product analytics suite","analytics","freemium","idea,mvp,growth","https://posthog.com",'["Open source","Feature flags","Session replay","Self-host option"]','["Can be complex to configure","High-volume storage costs"]'),
    ("amplitude","Amplitude","Digital analytics & behavioral insights","analytics","freemium","growth,scale","https://amplitude.com",'["Enterprise-grade","Behavioral cohorts","Best-in-class charts"]','["Expensive for small teams","Complex for simple needs"]'),
    ("plausible","Plausible","Privacy-friendly website analytics","analytics","paid","idea,mvp","https://plausible.io",'["GDPR-friendly","Lightweight script","Open source"]','["No funnel or event tracking","Very basic feature set"]'),
    ("simple-analytics","Simple Analytics","Clean, privacy-first web analytics","analytics","paid","idea,mvp","https://simpleanalytics.com",'["No cookies needed","Instant setup","Clean UI"]','["Very basic insights","Limited integrations"]'),
    # ── HOSTING (5) ──────────────────────────────────────────────────────────
    ("vercel","Vercel","Frontend cloud for modern web apps","hosting","freemium","idea,mvp,growth,scale","https://vercel.com",'["Instant deployments","Global edge network","Amazing DX"]','["Expensive at scale","Compute limitations"]'),
    ("railway","Railway","Infrastructure for the next generation","hosting","freemium","idea,mvp,growth","https://railway.app",'["Simple pricing","Managed DB included","Fast deploys"]','["Smaller community","Newer platform"]'),
    ("flyio","Fly.io","Run apps close to users worldwide","hosting","freemium","mvp,growth,scale","https://fly.io",'["Global edge deployment","Docker-native","Very affordable"]','["CLI-heavy workflow","Steeper learning curve"]'),
    ("render","Render","Cloud platform for modern applications","hosting","freemium","mvp,growth","https://render.com",'["Simple pricing","Auto-deploys from Git","Good free tier"]','["Slower cold starts","Primarily US regions"]'),
    ("heroku","Heroku","Cloud application platform (Salesforce)","hosting","paid","mvp,growth","https://heroku.com",'["Mature ecosystem","Easy deploys","Rich add-on marketplace"]','["No free tier","Expensive compared to alternatives","Slow builds"]'),
    # ── MONITORING (5) ───────────────────────────────────────────────────────
    ("sentry","Sentry","Application monitoring & error tracking","monitoring","freemium","mvp,growth,scale","https://sentry.io",'["Best error tracking","Smart alerting","Session replays"]','["Can be noisy","Expensive large-scale"]'),
    ("logrocket","LogRocket","Session replay & performance monitoring","monitoring","freemium","mvp,growth","https://logrocket.com",'["Full session replays","Performance insights","User context"]','["Pricey plans","Some privacy concerns"]'),
    ("datadog","Datadog","Full-stack cloud monitoring & APM","monitoring","paid","growth,scale","https://datadoghq.com",'["Comprehensive APM","Great log management","Powerful dashboards"]','["Very expensive","Overkill for early-stage MVPs"]'),
    ("betterstack","BetterStack","Uptime monitoring & status pages","monitoring","freemium","idea,mvp,growth","https://betterstack.com",'["Beautiful status pages","Uptime checks","On-call scheduling"]','["Newer platform","Limited deep APM"]'),
    ("cronitor","Cronitor","Cron job & task monitoring","monitoring","freemium","mvp,growth","https://cronitor.io",'["Easy cron monitoring","Heartbeat checks","Simple setup"]','["Niche use case","Limited beyond monitoring"]'),
    # ── DATABASE (5) ─────────────────────────────────────────────────────────
    ("supabase","Supabase","Open-source Firebase alternative","db","freemium","idea,mvp,growth","https://supabase.com",'["Postgres under the hood","Realtime subscriptions","Auth + Storage bundled","OSS"]','["Self-host complexity","Newer platform"]'),
    ("planetscale","PlanetScale","MySQL-compatible serverless database","db","freemium","mvp,growth,scale","https://planetscale.com",'["Database branching","Highly scalable","Zero-downtime schema changes"]','["No longer has free tier","MySQL only"]'),
    ("turso","Turso","SQLite for production at the edge","db","freemium","idea,mvp","https://turso.tech",'["Lightweight","Edge-native libSQL","Cheap for small apps"]','["SQLite limitations","Newer product"]'),
    ("neon","Neon","Serverless Postgres with branching","db","freemium","idea,mvp,growth","https://neon.tech",'["Serverless Postgres","DB branching for CI/CD","Scale to zero"]','["Newer platform","Cold start latency"]'),
    ("mongodb-atlas","MongoDB Atlas","Cloud-native document database","db","freemium","mvp,growth,scale","https://www.mongodb.com/atlas",'["Flexible schema","Global multi-region","Built-in Search & Analytics"]','["NoSQL complexity","Cost at scale","Not relational"]'),
    # ── AI (5) ───────────────────────────────────────────────────────────────
    ("openai","OpenAI API","GPT-4 & o-series models via API","ai","paid","idea,mvp,growth,scale","https://openai.com",'["Industry-best models","Huge ecosystem","Reliable uptime"]','["Expensive token costs","Rate limits","Data privacy concerns"]'),
    ("anthropic","Anthropic Claude","Helpful, harmless, honest AI API","ai","paid","idea,mvp,growth","https://anthropic.com",'["Safety-focused models","200K context window","Strong reasoning"]','["Pricier than alternatives","Fewer model variants"]'),
    ("replicate","Replicate","Run any AI model via API","ai","paid","idea,mvp","https://replicate.com",'["1000+ open models","Simple REST API","Image/video gen"]','["Cold start latency","Variable cost","Newer platform"]'),
    ("together-ai","Together AI","Fast inference for open-source models","ai","paid","mvp,growth","https://together.ai",'["High throughput","Open model ecosystem","Competitive pricing"]','["Smaller community","Fewer proprietary models"]'),
    ("groq","Groq","Ultra-fast LLM inference on LPU","ai","freemium","idea,mvp,growth","https://groq.com",'["Extremely fast tokens/sec","Free tier available","LPU hardware advantage"]','["Limited model selection","Rate limits on free tier"]'),
    # ── DESIGN (5) ───────────────────────────────────────────────────────────
    ("figma","Figma","Collaborative interface design tool","design","freemium","idea,mvp,growth,scale","https://figma.com",'["Industry standard","Real-time collaboration","Huge plugin ecosystem"]','["Expensive team plans","Slow with very large files"]'),
    ("canva","Canva","Visual content creation for everyone","design","freemium","idea,mvp","https://canva.com",'["Extremely easy to use","Thousands of templates","Non-designer friendly"]','["Not suitable for complex UI","Export limitations on free tier"]'),
    ("framer","Framer","Design & ship interactive websites","design","freemium","idea,mvp","https://framer.com",'["Production-ready outputs","CMS built-in","Smooth animations"]','["Pricey for teams","Learning curve","Niche tool"]'),
    ("webflow","Webflow","No-code web development platform","design","freemium","idea,mvp,growth","https://webflow.com",'["Powerful CMS","Good SEO control","Designer-friendly"]','["Steep learning curve","Expensive CMS plans","Vendor lock-in"]'),
    ("v0","v0 by Vercel","AI-powered UI component generator","design","freemium","idea,mvp","https://v0.dev",'["Instant shadcn/ui components","React-ready output","Great for MVPs"]','["Vercel-ecosystem tied","Generation limits","Beta quality"]'),
    # ── SUPPORT (5) ──────────────────────────────────────────────────────────
    ("intercom","Intercom","Customer engagement & messaging platform","support","paid","growth,scale","https://intercom.com",'["Feature-rich inbox","Product tours","AI chatbot"]','["Very expensive","Complex initial setup"]'),
    ("crisp","Crisp","Modern customer messaging platform","support","freemium","idea,mvp,growth","https://crisp.chat",'["Generous free tier","Live chat + email","Clean UI"]','["Limited automation on free tier","Basic AI features"]'),
    ("zendesk","Zendesk","Enterprise customer service software","support","paid","growth,scale","https://zendesk.com",'["Enterprise-grade","Highly scalable","Extensive integrations"]','["Very expensive","Overkill for small teams","Complex setup"]'),
    ("helpscout","Help Scout","Customer support for growing teams","support","paid","mvp,growth","https://helpscout.com",'["Email-first design","Simple clean UX","Docs & chat built-in"]','["No free tier","Limited live chat"]'),
    ("tawkto","Tawk.to","100% free live chat software","support","free","idea,mvp","https://tawk.to",'["Completely free","Easy 1-line install","Mobile app"]','["Tawk.to branding unless paid","Basic feature set"]'),
    # ── MARKETING (5) ────────────────────────────────────────────────────────
    ("buffer","Buffer","Social media scheduling & analytics","marketing","freemium","idea,mvp,growth","https://buffer.com",'["Simple UI","Multi-platform scheduling","Good free tier"]','["Limited analytics depth","Slower than native posting"]'),
    ("beehiiv","Beehiiv","Newsletter platform built for growth","marketing","freemium","idea,mvp,growth","https://beehiiv.com",'["Growth-first features","Built-in analytics","Referral program & monetization"]','["Newer platform","Limited third-party integrations"]'),
    ("typefully","Typefully","Twitter/X content scheduling tool","marketing","freemium","idea,mvp","https://typefully.com",'["Thread scheduling","Analytics dashboard","Clean focused UI"]','["X-only platform","Limited cross-platform support"]'),
    ("hubspot","HubSpot","CRM & inbound marketing platform","marketing","freemium","mvp,growth,scale","https://hubspot.com",'["Free CRM tier","All-in-one suite","Powerful automation"]','["Gets expensive fast","Complex & feature-bloated","Slow UI"]'),
    ("mailchimp","Mailchimp","Email marketing & automation","marketing","freemium","idea,mvp,growth","https://mailchimp.com",'["Easy to use","Drag-drop templates","Good automation builder"]','["Pricey at scale","Deliverability issues","Outdated UI"]'),
    # ── DEV TOOLS (5) ────────────────────────────────────────────────────────
    ("github","GitHub","Code hosting & collaboration platform","dev","freemium","idea,mvp,growth,scale","https://github.com",'["Industry standard","GitHub Actions CI/CD","Copilot AI coding"]','["Expensive large-team plans","Microsoft-owned"]'),
    ("linear","Linear","Issue tracking for modern software teams","dev","freemium","idea,mvp,growth","https://linear.app",'["Blazing fast UI","Beautiful & opinionated","Great keyboard shortcuts"]','["Opinionated workflow","No free tier long-term"]'),
    ("notion","Notion","All-in-one workspace for teams","dev","freemium","idea,mvp","https://notion.so",'["Extremely flexible","Docs + DB + Wiki","Built-in AI features"]','["Can be slow","Easy to over-engineer","Not ideal for large teams"]'),
    ("jira","Jira","Project tracking for software teams","dev","freemium","growth,scale","https://atlassian.com/software/jira",'["Very powerful","Deep Atlassian ecosystem","Highly customizable"]','["Complex & bloated","Expensive","Steep learning curve"]'),
    ("cursor","Cursor","AI-first code editor","dev","freemium","idea,mvp,growth","https://cursor.com",'["AI-native editing","VSCode-compatible","Fast autocomplete"]','["Subscription cost","Privacy considerations","Newer product"]'),
]
